# Mod info
mod_name=NBT Autocomplete
mod_jar_name=NBTac
mod_id=nbtac
mod_group=net.mt1006.nbtac
mod_author=mt1006
version=2.0
license=LGPL-3.0-only
homepage=https://modrinth.com/mod/nbt-autocomplete
source_url=https://github.com/mt1006/mc-nbtac-mod
issue_tracker=https://github.com/mt1006/mc-nbtac-mod/issues
mod_description=Adds suggestions for NBT tags.

# Minecraft and Java
minecraft_version=1.21.4
java_version=21

# Requires
version_range_fabric=>=1.21.4 <1.21.5
version_range_neoforge=[1.21.4,1.21.5)

# Loaders
# https://github.com/FabricMC/fabric-loader/releases
# https://modrinth.com/mod/fabric-api/versions?c=release
# https://projects.neoforged.net/neoforged/neoforge
fabric_loader_version=0.19.5
fabric_api_version=0.119.4+1.21.4
neoforge_version=21.4.157

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Gradle dependencies
# https://github.com/FabricMC/fabric-loom/releases
# https://projects.neoforged.net/neoforged/ModDevGradle
fabric_loom_version=1.17-SNAPSHOT
neoforge_moddev_version=2.0.146

# Other dependencies
# https://modrinth.com/mod/modmenu/versions
modmenu_version=13.0.4

# Gradle configuration
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.problems.report=false
