# Mod info
mod_name=NBT Autocomplete
mod_jar_name=NBTac
mod_id=nbt_ac
mod_group=com.mt1006.nbt_ac
mod_author=mt1006
version=1.3.11
license=LGPL-3.0-only
homepage=https://modrinth.com/mod/nbt-autocomplete
source_url=https://github.com/mt1006/mc-nbtac-mod
issue_tracker=https://github.com/mt1006/mc-nbtac-mod/issues
mod_description=Adds suggestions for NBT tags.

# Minecraft and Java
minecraft_version=1.21.4
java_version=21

# Requires
version_range_fabric=>=1.21.4
version_range_neoforge=[1.21.4,)

# Loaders
# https://github.com/FabricMC/fabric-loader/releases
# https://modrinth.com/mod/fabric-api/versions?c=release
# https://projects.neoforged.net/neoforged/neoforge
fabric_loader_version=0.16.9
fabric_api_version=0.112.2+1.21.4
neoforge_version=21.4.39-beta

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.21.4
parchment_version=2024.12.22

# Gradle dependencies
# https://github.com/FabricMC/fabric-loom/releases
# https://projects.neoforged.net/neoforged/ModDevGradle
fabric_loom_version=1.9-SNAPSHOT
neoforge_moddev_version=2.0.62-beta

# Other dependencies
# https://modrinth.com/mod/modmenu/versions
modmenu_version=13.0.0-beta.1

# Gradle configuration
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.problems.report=false
